version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'DashB'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '139'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8092
    volumes:
      - .:/app
    ports:
      - "8092:8092"
    depends_on:
      - db


