version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'DashB'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '139'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8093
    volumes:
      - .:/app
    ports:
      - "8093:8093"
    depends_on:
      - db
volumes:
  pgdata:

