version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8092
    volumes:
      - .:/app
    ports:
      - "8092:8092"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'DashB'
      POSTGRES_USER: 'postgres1'
      POSTGRES_PASSWORD: '139'
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

