version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: DashB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 139

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8092"
    volumes:
      - .:/app
    ports:
      - "8092:8092"
    depends_on:
      - db
    environment:
      POSTGRES_DB: DashB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 139
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
