version: '3'

services:
  web:
    image: hajer139/dashdor
    command: python manage.py runserver 0.0.0.0:8091
    volumes:
      - .:/app
    ports:
      - "8091:8091"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'DashB'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '139'
    ports:
      - "5432:5432"
